---
driver:
  name: vagrant
#  vagrantfiles:
#    - Vagrant_Proxy.rb

provisioner:
  name: puppet_apply
  manifests_path: ../Puppet/manifests
  modules_path: ../Puppet/modules
  hiera_data_path: ../Puppet/hieradata

platforms:
  - name: centos-6.6
    driver_plugin: vagrant
    driver_config:
      box: puppetlabs/centos-6.6-64-nocm
#  - name: centos-7.0
#    driver_config:
#      box: centos-7.0
#  - name: puppetlabs/ubuntu-14.04-64-nocm
#    driver_config:
#      box: puppetlabs/ubuntu-14.04-64-nocm
#  - name: debian-7.8
#    driver_config:
#      box: puppetlabs/debian-7.8-64-nocm

suites:
  - name: default
    manifests: site.pp
